# Funciones

Dijimos que en python podemos definir nuestras propias funciones y reutilizarlas donde querramos. 

Como lo hacemos?

Una función en python se define de la siguiente manera:



```
def nombre_de_la_función(parametro1, parametro2):
  ...
  bloque de código
  ...
  return algunValor # Opcional
```

Una función puede recibir 0 o tantos parámetros como necesitemos y opcionalmente retornar algún valor

Para llamarla simplemente escribimos su nombre y le pasamos los parámetros que necesite (si es que necesita)

Veamos algunos ejemplos:

In [ ]:
# Función que no recibe parámetros y no retorna ningún valor
def nuestra_funcion():
  print("Nuestra primer funcion que no retorna nada y simplemente imprime un mensaje")

In [ ]:
i = 0
while i <= 5:
  nuestra_funcion()
  i += 1 # Esto es lo mismo que escribir i = i + 1

Nuestra primer funcion que no retorna nada y simplemente imprime un mensaje
Nuestra primer funcion que no retorna nada y simplemente imprime un mensaje
Nuestra primer funcion que no retorna nada y simplemente imprime un mensaje
Nuestra primer funcion que no retorna nada y simplemente imprime un mensaje
Nuestra primer funcion que no retorna nada y simplemente imprime un mensaje
Nuestra primer funcion que no retorna nada y simplemente imprime un mensaje


In [ ]:
# Función que recibe parámetros pero no retorna ningún valor

def otra_funcion(parametro):
  print(f"parametro toma el valor: {parametro}")

otra_funcion("un valor")
otra_funcion(5)
otra_funcion([1,2,3])

parametro toma el valor: un valor
parametro toma el valor: 5
parametro toma el valor: [1, 2, 3]


In [ ]:
# Función que recibe parámetros y retorna un valor

def suma(a, b):
  return a + b

In [ ]:
c = suma(5, 6)
print(c)

11


##### Docstrings

Es una muy buena práctica, documentar lo que hacemos. Muchas veces otras personas van a ver nuestro código, nuestros análisis en jupyter notebooks, etc y no es simple ver el código de otra persona cuando no hay ningún comentario.

Tenemos que acostumbrarnos desde ahora a comentar bien las funciones que hacemos y aprovechar las celdas de texto que nos brinda jupyter para explicar lo que vamos haciendo.

En python, una forma de describir lo que hace una función es usando docstings. Esto es, una descripción que se pone entre 3 comillas """ al principio de la funcion. Por ejemplo:

In [ ]:
def suma(a, b):
  """
  Esta funcion retorna la suma de los valores de a y b.
  Params:
  - a: número a (int)
  - b: número b (int)
  """
  return a + b

Otra buena práctica, es especificar el tipo de dato que esperamos que reciba una función y el tipo de dato que devuelve. Esto se hace de la siguiente forma:

In [ ]:
def suma(a: int, b: int) -> int:
  """
  Esta funcion retorna la suma de los valores de a y b.
  Params:
  - a: número a (int)
  - b: número b (int)
  """
  return a + b

Además, cuando definimos una función con docstings, al utilizar la funcion `help`de python, ese docstring se imprime y puede ser muy util para otra persona que quiera usar nuestra función!

In [ ]:
help(suma)

Help on function suma in module __main__:

suma(a: int, b: int) -> int
    Esta funcion retorna la suma de los valores de a y b.
    Params:
    - a: número a (int)
    - b: número b (int)



Parametros por defecto

In [1]:
def resta(a=None, b=None):
    if a == None or b == None:
        print("Error, debes enviar dos números a la función")
        return   # indicamos el final de la función aunque no devuelva nada
    else: 
      return a-b

resta()

Error, debes enviar dos números a la función


# Ejercicios

1) Realiza una función llamada `relacion(a, b)` que a partir de dos números cumpla lo siguiente:

Si el primer número es mayor que el segundo, debe devolver 1.
Si el primer número es menor que el segundo, debe devolver -1.
Si ambos números son iguales, debe devolver un 0.


2) Realiza una función `separar(lista)` que tome una lista de números enteros y devuelva dos listas ordenadas. La primera con los números pares y la segunda con los números impares.



# Numpy

Recuerden que siempre pueden tener la documentación a mano cuando necesitan algo: https://numpy.org/doc/stable/

En esta clase vamos a empezar a aprender las principales funcionalidades que nos brinda numpy.

Lo primero que tenemos que hacer siempre que vayamos a usar una librería, es instalarla.

En python, las librerías se pueden instalar con el comando `pip install NombreDeLaLibreria` o en el caso de que estemos en un environment de conda, 'conda install'.

Siempre en la documentación de una librería nos van a explicar como instalarla.

Si instalamos anaconda o usamos google colab, numpy ya viene instalado. Si no, debemos correr el siguiente comando:

In [ ]:
!pip install numpy

Vemos que dice: Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.19.5)

Esto quiere decir que ya la teníamos instalada desde antes.

Una vez que instalamos una librería, tenemos que importarla para poder usarla. En python, esto se hace de la siguiente manera:

In [ ]:
import numpy as np

La parte que dice `as np` se denomina alias. Esto es para que cuando querramos llamar a la librería, no tengamos que poner su nombre completo y podamos llamarla simplemente con el alias `np`.

## Numpy array

El elemento principal de numpy es el numpy array. Para crear uno hay varias formas, una de ellas es pasándo una lista como parámetro:

In [ ]:
lista = [1,2,3,4]
numpy_array = np.array(lista)
print(lista)
print(numpy_array)

[1, 2, 3, 4]
[1 2 3 4]


En este caso, en el que el array esta compuesto por un rango de números en forma ascendente, numpy nos brinda formas más rapidas de crear un array:

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

Este array empieza desde 0, nuestra lista anterior arrancaba desde 1. ¿ Cómo podremos hacer que el array arranque desde 1 ?
Para responder preguntas de este tipo, la documentación y el comando help() son muy útiles.

Veamos que dice el comando help:

In [ ]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

Ahora, tratemos de generar un array de 6 elementos que arranque desde el valor 0!

In [ ]:
nuevo_array = np.arrange( ... ) # COMPLETAR
print(nuevo_array)

### Operaciones sobre listas y arrays de numpy

Otra funcionalidad muy útil que nos provee numpy, es la posibilidad de realizar una operación matemática sobre cada elemento de la lista de una forma muy simple.

Si queremos hacer esto con una lista común de python, vamos a necesitar iterar sobre cada elemento (con un for). Numpy nos ahorra ese paso:

In [ ]:
# Al hacerlo sobre una lista, vamos a obtener un error:

[1,2,3] + 1

TypeError: ignored

In [ ]:
# Si queremos hacerlo sobre una lista tenemos que usar list comprehension

l = [1,2,3,4,5,6]
l_sum = [item + 1 for item in l]
l_sum

[2, 3, 4, 5, 6, 7]

In [ ]:
# Pero sobre un numpy array, lo podemos hacer simplemente sumando un número:

np.arange(10) + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(10) * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

### Arrays multidimensionales

Al igual que las listas, los arrays de numpy pueden ser n-dimensionales

In [ ]:
n_dimensiones = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10, 11, 12]]])
n_dimensiones

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Shape

Vimos que los arrays de numpy tienen un atributo que se llama `shape`. Esto nos dice la "forma" que tiene el array. Veamos un ejemplo:

In [ ]:
n_dimensiones.shape

(2, 2, 3)

El shape de un array puede modificarse con la función reshape() de numpy:

In [ ]:
una_dim = np.arange(5)
una_dim

array([0, 1, 2, 3, 4])

In [ ]:
una_dim.shape

(5,)

In [ ]:
# (filas, columnas)
una_dim = una_dim.reshape(5, 1)
una_dim

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
una_dim = una_dim.reshape(1, 5)
una_dim

array([[0, 1, 2, 3, 4]])

### Linspace

La función linspace de numpy, nos permite crear arreglos de una forma similar a arange().

La diferencia con arange() es que en esta función, se crean n elementos igualmente espaciados en un intervalo que definamos.

Por ejemplo, si queremos crear un array de 10 elementos igualmente espaciados entre 0 y 1:

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Recuerden que siempre se puede usar help!

In [ ]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

Y también tenemos documentación: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

### Zeros y Ones

Numpy también nos permite crear un array de tantos 0s o 1s como querramos

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

O podemos usar la función full() y crear un array con la shape que querramos y el valor que querramos:

In [ ]:
np.full(shape=(10,10), fill_value=3)

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

### Acceder a elementos del array

Al igual que una lista, para acceder a los elementos de un array de numpy podemos utilizar el indice de los elementos que querramos o un rango [start:stop:step]

In [ ]:
numpy_array[1]

2

In [ ]:
numpy_array[0:3]

array([1, 2, 3])

### Mask

Muchas veces vamos a tener arrays enormes con datos y queremos filtrarlos. Por ejemplo, de un array queremos obtener todos los números que sean menores a 10.

Para hacer esto en una lista de python, deberíamos iterar sobre toda la lista. Podemos evitarlo usando masks en numpy.

Las masks (o filtros booleanos) se definen como una condición, por ejemplo para el caso en el que queremos saber si un elemento es < 10:

`lista < 10`

Esto nos va a retornar otra lista (con el mismo shape que la lista a la que le aplicamos la mask) pero que va a contener los valores `True` y `False`.

True en los casos que se cumple la condición, False de lo contrario.


In [ ]:
lista_a_filtrar = np.arange(100).reshape(10, 10) # Creamos una lista de 100 elementos con shape (10, 10), es decir, 10 filas y 10 columnas
lista_a_filtrar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# Definimos la Mask

mask = lista_a_filtrar < 10
mask

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

Ahora, la Mask nos retorna otra lista con valores booleanos, pero si queremos usar esto para filtrar (aplicar la mascara), como hacemos?

Es simple, se define de la siguiente manera:

In [ ]:
lista_filtrada = lista_a_filtrar[mask]
lista_filtrada

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Las máscaras no sirven solo para filtrar, también podemos asignar un valor a los elementos que cumplan la condición. Veamos un ejemplo: Reemplacemos todos los elementos que sean menores a 10 por el numero 10:

In [ ]:
lista_elementos = np.arange(20)
mask = lista_elementos < 10
lista_elementos[mask] = 10 # Asignamos el valor "menor" a todos los items que cumplen la condicion
lista_elementos

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Otras funciones

No podemos ver todas las funciones que nos brinda numpy en una clase, pero vamos a ver algunas de las más comunes ya que el resto tiene una sintaxis similar.

Si queremos sumar todos los elementos de un array:

In [ ]:
lista_a_filtrar.sum()

4950

En numpy, las funciones se pueden aplicar por "axis" (eje). Por ejemplo, podemos aplicar la función sum() sobre cada columna:

In [ ]:
# Por columnas

lista_a_filtrar.sum(axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

O sobre cada fila:


In [ ]:
# Por filas

lista_a_filtrar.sum(axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

# A practicar!

Ahora que vimos algunas funcionalidades de numpy, vamos a resolver algunos problemas. Acuerdense de modificar, romper y arreglar todo lo que quieran!

Probablemente necesiten buscar algo en la documentación o utilizar el comando help().


#### Ejercicio

Crear un array de 3x3 en el que todos sus valores sean `True` de la forma más simple posible

In [ ]:
trues_array = #COMPLETAR
trues_array

#### Ejercicio

Reemplazar todos los números impares del siguiente array por el valor -1

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = # COMPLETAR
#COMPLETAR

#### Ejercicio

Investigar las funciones vstack y hstack de numpy.

1) Concatenar los arrays a y b horizontalmente

2) Concatenar los arrays a y b verticalmente

Resultado esperado:

1)
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

2)
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
      [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```



In [ ]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5) 

In [ ]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]]


##### Ejercicio

Como podemos obtener la intersección entre dos arrays? 

Investigar la función `intersect1d` y utilizarla para los siguientes arrays:

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# COMPLETAR

In [ ]:
# Salida esperada: array([2, 4])